---
# minimal_tmux_configuration/tasks/main.yml

- name: 'Set primary group to users on SUSE/openSUSE'
  ansible.builtin.set_fact:
    primary_group_name: 'users'
  when: '
    ansible_distribution == "SLES" or
    ansible_distribution == "openSUSE Leap" or
    ansible_distribution == "openSUSE MicroOS" or
    ansible_distribution == "openSUSE Tumbleweed"
    '

- name: 'Set root_group to wheel on FreeBSD'
  ansible.builtin.set_fact:
    root_group: 'wheel'
  when:
    - 'ansible_os_family == "FreeBSD"'

#
#
#

- name: 'Install tmux'
  ansible.builtin.package:
    name: 'tmux'
    state: 'present'
  when:
    - not ansible_pkg_mgr == "atomic_container"
    - ansible_distribution != "openSUSE MicroOS"

- name: 'Install package tmux on Fedora CoreOS'
  community.general.rpm_ostree_pkg:
    name:
      - 'tmux'
  notify:
    - 'Reboot on CoreOS'
  when:
    - ansible_pkg_mgr == "atomic_container"
    - ansible_distribution != "openSUSE MicroOS"

#
# currently fails with 'failed to parse zypper xml output: no element found: line 1, column 0'
#
# - name: 'Install package tmux data on openSUSE MicroOS with a reboot'
#   community.general.zypper:
#     name:
#       - 'tmux'
#     update_cache: true
#   notify:
#     - 'Reboot on openSUSE MicroOS'
#   when:
#     - ansible_distribution == "openSUSE MicroOS"

- name: 'Install package tmux on openSUSE MicroOS with a reboot'
  ansible.builtin.command:
    cmd: /usr/sbin/transactional-update --non-interactive --continue pkg in tmux
  register: package_install_output
  changed_when:
    - "'zypper: nothing to update' not in package_install_output.stdout"
  notify:
    - 'Reboot on openSUSE MicroOS'
  when:
    - ansible_distribution == "openSUSE MicroOS"

- name: 'Create .tmux.conf for root'
  ansible.builtin.template:
    src: 'tmux.conf.j2'
    dest: '/root/.tmux.conf'
    owner: 'root'
    group: "{{ root_group | default('root') }}"
    mode: '0644'
  when:
    - 'tmuxconf_for_root | bool'

- name: 'Create .tmux.conf for other users (if any are supplied)'
  ansible.builtin.template:
    src: 'tmux.conf.j2'
    dest: "/home/{{ item }}/.tmux.conf"
    owner: "{{ item }}"
    group: "{{ primary_group_name | default(item) }}"
    mode: '0644'
  with_items:
    - "{{ additional_users }}"
  when:
    - 'additional_users is defined'
